### ISSUE TITLE
Signed version of the NuGet package

### ISSUE THREAD

**Issue by PashCracken** [jsakamoto/ipaddressrange#22]
Hi,

Can you please add a IPAddressRange.Signed version of the NuGet package or sign the dll in the existing package? We want to use this NuGet package in several projects that is signed. I would really like to avoid having to create a locally signed version myself so I hope you will be able to do this

**Comment by jsakamoto** [comment]
OK, I would like to try it.

But I'm busy in these days, so please let me a few days.

**Comment by PashCracken** [comment]
Great. Thanks

**Comment by PashCracken** [comment]
Any progress on this?

**Comment by M-Zuber** [comment]
There are a number of tools that can be easily integrated into a build system that will sign dlls for you.
https://github.com/dsplaisted/strongnamer (nuget package) (probably the simplest option)
https://github.com/brutaldev/StrongNameSigner (tool, call from msbuild target/csproj file) (manual editing)
https://github.com/oising/strongnaming (powershell cmdlets) (most manual)

**Comment by jsakamoto** [comment]
@PashCracken Sorry, I had much drink tonight (JST), and I attend "de:code 2016" Microsoft IT conference in Tokyo, Japan, so I could not any work...

I'll work at least next week.

**Comment by jsakamoto** [comment]
@M-Zuber Thank you for your information. It is very helpful for me.

**Comment by PashCracken** [comment]
@jsakamoto Is there a signed package available now?

**Comment by jsakamoto** [comment]
@PashCracken Sorry to late.

I released signed version right now.

- https://github.com/jsakamoto/ipaddressrange/tree/release/signed-version
- https://www.nuget.org/packages/IPAddressRange.Signed/

Is this your expected one?
If it is true, then I'll republish the package as GA version (v.1.6.0-rc1 => v.1.6.0) as soon as possible.

**Comment by PashCracken** [comment]
@jsakamoto Perfect. Just what I wanted :+1:

**Comment by PashCracken** [comment]
When do you think you will have published v1.6.0 of the signed package?

**Comment by jsakamoto** [comment]
@PashCracken I did it :)

https://www.nuget.org/packages/IPAddressRange.Signed/

**Comment by PashCracken** [comment]
Thanks :-)

**Comment by jsakamoto** [comment]
I'm feeling very unhappy now :cry: because my PC's storage was broken at 3 days ago.

So **I lost private key for signing assembly**...OMG. 😭

I had trying to recovery my PC and salvage key file, but I understood there is no hope at last.

In normally situation, I always create offline backup of key file.  
But in this case,

1. I'm in business trip, so I don't have offline backup media ( I keep offline backup media in my home, and I don't bring out it never )
2. I take a priority for release signed version.
3. But my PC broken before I go home...!

So I have to decide that I should recreate new key.  
I'll republish `IPAddressRange.Signed` which signed by new key as soon as possible.

I hope everyone can forgive me.

**Comment by jsakamoto** [comment]
I publish new package as Release Candidate.

https://www.nuget.org/packages/IPAddressRange.Signed/1.6.0.1-rc1

**Comment by PashCracken** [comment]
No problem. Just publish the release version with a new key

**Comment by jsakamoto** [comment]
@PashCracken Thanks.

I published `IPAddressRange.Signed` v.1.6.0.1. ( http://www.nuget.org/packages/IPAddressRange.Signed/1.6.0.1 )
