### ISSUE TITLE
IPAddressRange should be updated to handle multiple target frameworks.

### ISSUE THREAD

**Issue by DerekChasse** [jsakamoto/ipaddressrange#30]
With the official release of .NET Core 2.0 IPAddressRange should be updated to target this additional framework.

**Comment by jsakamoto** [comment]
Since v.1.6.2, IPAddressRange already supported .NET Standard 1.4.

So you can install IPAddressRange latest version in your .NET Core 2.0 application project.

By the way, the package v.2.0.0.3 causes warning about "Could not find NETStandard.Library package v.1.4 in nuget.org".  
This warning is no problem.  
But I updated the package to v.2.0.0.4 for avoiding this warning by upgrading reference NETStandard.Library package version from 1.4 to 1.6.

![image](https://user-images.githubusercontent.com/95908/30483329-8afe72e2-9a61-11e7-88f3-5c25e5708974.png)
