### ISSUE TITLE
Cant parse example string

### ISSUE THREAD

**Issue by gaazkam** [jsakamoto/ipaddressrange#47]
Installed IPAddressRange v. 3.2.0 via NuGet

In the comments of your source file: https://github.com/jsakamoto/ipaddressrange/blob/master/IPAddressRange/IPAddressRange.cs

We see such a comment:

> // Pattern 3. Begin end range: "169.258.0.0-169.258.0.255", "fe80::1%23-fe80::ff%23"

But Your lib fails to parse this very example string!

    using NetTools;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Threading.Tasks;

    namespace ConsoleApp2
    {
        class Program
        {
            static void Main(string[] args)
            {    
                string ipstring = "169.258.0.0-169.258.0.255";
                IPAddressRange iprange = IPAddressRange.Parse(ipstring);
                Console.WriteLine(iprange.ToString());
                Console.ReadKey();
            }
        }
    }

This throws!  `System.FormatException` And `TryParse` returns false

**Comment by jsakamoto** [comment]
I'm sorry that the comments is invalid.

"192.**258**.0.0" is invalid IPv4 address, because a part of IPv4 address which is separated by dot(.) is representation of 8 bit value.  
Therefore, the value **258** is invalid. (8 bit value can represent from 0 to 255.)

![image](https://user-images.githubusercontent.com/95908/46898593-84ff4080-cec5-11e8-9b71-a7c0fbfbc062.png)

I fixed those comments just now.

https://github.com/jsakamoto/ipaddressrange/commit/f172285b853faa4e93f2c2bff0261611a42d4763#diff-84e5184cbe9467997f4166539b02496e

Thank you for your reporting! 👍
