### ISSUE TITLE
Parse / TryParse

### ISSUE THREAD

**Issue by M-Zuber** [jsakamoto/ipaddressrange#5]
The addition of such functionality would add a lot to this package

**Comment by M-Zuber** [comment]
I hope to have a PR ready soon

**Comment by jsakamoto** [comment]
Thank you for your pull request #6 :)

I think, adding ```TryParse``` static method is a good idea. But adding ```Parse``` static method would cause confusing among the library users, dosen't it?

"What difference does ```new IPAddressRange(...)``` and ```IPAddressRange.Parse(...)```?"

Could you tell me your opinion about needs of ```Parse``` method?

**Comment by M-Zuber** [comment]
The reason I feel to add a `Parse` method is more due to convention. I see it is being the second half of a pair together with `TryParse`.
I have no problem removing it though.

**Comment by jsakamoto** [comment]
Thank you for your reply.

＞I see it is being the second half of a pair together with TryParse.

I'll drink to that.

Well, I would like to consider well to obsoloete public constructor instead of adding ```Parse``` static method. (That means I'll conceal the constructor to private access control.)

Please give me some time to work :)

**Comment by M-Zuber** [comment]
:+1: Take you time

**Comment by jsakamoto** [comment]
Thank you for waiting.

I merged it and publish new package v.1.2!  
http://www.nuget.org/packages/IPAddressRange/

Thank you for your suggestion. :smile:

**Comment by M-Zuber** [comment]
Pleasure!
